
// 389. Find the Difference : https://leetcode.com/problems/find-the-difference/
import java.util.*;

public class LeetCode_Find_the_Difference {

    static char findTheDifference(String s, String t) {
        HashMap<Character, Integer> maps = new HashMap<>();
        for (int i = 0; i < s.length(); i++) {
            if (maps.containsKey(s.charAt(i)))
                maps.put(s.charAt(i), 1 + maps.get(s.charAt(i)));
            else
                maps.put(s.charAt(i), 1);
        }
        for (int i = 0; i < t.length(); i++) {
            if (maps.containsKey(t.charAt(i)))
                maps.put(t.charAt(i), maps.get(t.charAt(i)) - 1);
            else
                maps.put(t.charAt(i), 1);
        }
        for (Character key : maps.keySet()) {
            return key;
        }
        return ' ';
    }

    public static void main(String[] args) {
        String s = "a";
        String t = "aa";
        char ans = findTheDifference(s, t);
        System.err.println(ans);
    }
}

// Output
// Input: s = "abcd", t = "abcde"
// Output: "e"
// Explanation: 'e' is the letter that was added.

// Input: s = "", t = "y"
// Output: "y"

// Explanation : You are given two strings s and t.
// String t is generated by random shuffling string s and then add one more
// letter at a random position.
// Return the letter that was added to t.